### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by shmilylty** [saghul/pycares#103]
os:win10
python:python3.8b4
```
pip3.8 -install pycares
```
```
ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shmily\\AppData\\Local\\Temp\\pip-install-kzuqorha\\pycares\\setup.py'"'"'; __file__='"'"'C:\\Users\\shmily\\AppData\\Local\\Temp\\pip-install-kzuqorha\\pycares\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\shmily\AppData\Local\Temp\pip-install-kzuqorha\pycares\
    Complete output (80 lines):
    Traceback (most recent call last):
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        with DirectorySandbox(setup_dir):
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 399, in __init__
        self._exceptions = [
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 400, in <listcomp>
        os.path.normcase(os.path.realpath(path))
      File "c:\program files\python38\lib\ntpath.py", line 592, in realpath
        path = _getfinalpathname_nonstrict(path)
      File "c:\program files\python38\lib\ntpath.py", line 566, in _getfinalpathname_nonstrict
        path = _readlink_deep(path, seen)
      File "c:\program files\python38\lib\ntpath.py", line 536, in _readlink_deep
        path = _nt_readlink(path)
    OSError: [WinError 1] 函数不正确。: 'nul'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shmily\AppData\Local\Temp\pip-install-kzuqorha\pycares\setup.py", line 15, in <module>
        setup(name             = 'pycares',
      File "c:\program files\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\program files\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\program files\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\program files\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\program files\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\program files\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\program files\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\program files\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\program files\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\program files\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\program files\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\program files\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\program files\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\program files\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\program files\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        with DirectorySandbox(setup_dir):
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 399, in __init__
        self._exceptions = [
      File "c:\program files\python38\lib\site-packages\setuptools\sandbox.py", line 400, in <listcomp>
        os.path.normcase(os.path.realpath(path))
      File "c:\program files\python38\lib\ntpath.py", line 592, in realpath
        path = _getfinalpathname_nonstrict(path)
      File "c:\program files\python38\lib\ntpath.py", line 566, in _getfinalpathname_nonstrict
        path = _readlink_deep(path, seen)
      File "c:\program files\python38\lib\ntpath.py", line 536, in _readlink_deep
        path = _nt_readlink(path)
    OSError: [Errno 22] 函数不正确。: 'nul'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by saghul** [comment]
Pycares 3.1.0 is now availablw with wheels also for Python 3.8: https://pypi.org/project/pycares/3.1.0/#files
