### ISSUE TITLE
Error FileNotFound when installing pycares==4.1.1

### ISSUE THREAD

**Issue by navoiee** [saghul/pycares#165]
Version 4.1.1 fails to install from pypi because of `FileNotFoundError` (PYPIREADME.rst)

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7p/jd8d_ynj3p927nzzd_ksww4h0000gn/T/pip-install-4wuwav9_/pycares_2655a73715204e54b42dd9fdd892b646/setup.py", line 23, in <module>
        long_description = codecs.open('PYPIREADME.rst', encoding='utf-8').read(),
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'PYPIREADME.rst'

**Comment by enricodvn** [comment]
I am having this issue also, with python 3.6 and pip version 19.0.3

**Comment by saghul** [comment]
Oops.

**Comment by saghul** [comment]
I just released https://github.com/saghul/pycares/releases/tag/pycares-4.1.2 it'll take a few minutes for the release to be pushed to PyPI. Sorry everyone!
