### ISSUE TITLE
test_query_class_chaos started failing

### ISSUE THREAD

**Issue by mgorny** [saghul/pycares#187]
I'm pretty sure it used to pass before, I think something on the remote server changed:

```pytb
======================================================================
FAIL: test_query_class_chaos (tests.test_all.DNSTest.test_query_class_chaos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pycares/tests/test_all.py", line 367, in test_query_class_chaos
    self.assertNoError(self.errorno)
  File "/tmp/pycares/tests/test_all.py", line 42, in assertNoError
    self.assertEqual(errorno, None)
AssertionError: 12 != None
```

Reproduced with d62a60c6abb20d8b16e1de287863659bc0163a3d, using Python 3.11.3 and c-ares from submodule (but happens with system c-ares 1.19.1 too).

**Comment by saghul** [comment]
All tests are passing now.
