### ISSUE TITLE
Error on Win8.1x64

### ISSUE THREAD

**Issue by constverum** [saghul/pycares#32]
Hi!

When I run the [aiodns example code](https://github.com/saghul/aiodns#example) on Windows 8.1 x64 (Python 3.5.1; pycares 2.0.1, aiodns 1.0.1, cffi 1.6.0) an error occurs:

```
Fatal Python error: ffi.from_handle() detected that the address passed points to
garbage. If it is really the result of ffi.new_handle(), then the Python object
has already been garbage collected

Thread 0x00000498 (most recent call first):
  File "..\lib\threading.py", line 293 in wait
  File "..\lib\threading.py", line 549 in wait
  File "..\lib\site-packages\IPython\core\history.py", line 804 in run
  File "..\lib\site-packages\IPython\core\history.py", line 68 in needs_sqlite
  File "<decorator-gen-23>", line 2 in run
  File "..\lib\threading.py", line 914 in _bootstrap_inner
  File "..\lib\threading.py", line 882 in _bootstrap

Current thread 0x00000fe8 (most recent call first):
  File "..\lib\site-packages\pycares\_cfficore\__init__.py", line 122 in _sock_state_cb
  File "..\lib\site-packages\pycares\_cfficore\__init__.py", line 455 in process_fd
  File "..\lib\site-packages\pycares\_cfficore\__init__.py", line 113 in wrapper
  File "..\lib\site-packages\aiodns\__init__.py", line 103 in _handle_event
  File "..\lib\asyncio\events.py", line 125 in _run
  File "..\lib\asyncio\base_events.py", line 1254 in _run_once
  File "..\lib\asyncio\base_events.py", line 295 in run_forever
  File "..\lib\asyncio\base_events.py", line 325 in run_until_complete
  ...
```

[Another example of this error](https://github.com/constverum/ProxyBroker/issues/11#issue-158472384).

Also one test is failed:

```
======================================================================
FAIL: test_query_ns (__main__.DNSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "..\pycares-master\tests\tests.py", line 162, in test_query_ns
    self.assertEqual(self.errorno, None)
AssertionError: 12 != None

----------------------------------------------------------------------
Ran 25 tests in 3.406s

FAILED (failures=1, skipped=5)
```
Meanwhile pycares 1.0 works fine and stable.

P.S. thank you very much for aiodns and pycares ;)

**Comment by saghul** [comment]
Do you get the same results if you use the C backend? The CFFI backend just landed in 2.0.0, so there might be some edge cases here and there. The test suite passes in AppVeyor, but hey, things can fail :-)

So, if you can, I'd recommend that you use the C core backend. If you are using the standard Python distribution, you can just install pycares from the wheels on PyPI and that should do.

**Comment by constverum** [comment]
I think I understand where the problem is.

> Do you get the same results if you use the C backend?

No, when I use the C backend is working fine.

> If you are using the standard Python distribution, you can just
install pycares from the wheels on PyPI and that should do.

And here is the problem =)

On PyPI all wheels are supplied with the compiled core (C core backend). 
Except the last one - pycares-2.0.1-cp35-cp35m-win_amd64.whl: 
It comes without the compiled core and uses CFFI, see [PYCARES_CFFI](https://github.com/saghul/pycares/blob/b64d53fa5e0bec098af2a1eda95a0dabd8baa94e/appveyor.yml#L46).

As an option may be to place the block with the `force build CFFI` penultimate. And then on PyPI will be sent wheel with the compiled core.

**Comment by saghul** [comment]
Oh, sorry about that! I thought I had picked the good ones. Can you test this wheel out? https://ci.appveyor.com/project/saghul/pycares/build/1.0.65/job/yb5psv3alabaem0m/artifacts

That one should be the one with the C core backend. I'll fixup that for the next release, but alas PyPI doesn't allow to replace already uploaded binaries.

**Comment by constverum** [comment]
Tested the wheel, works great! =)

**Comment by saghul** [comment]
Glad to hear! I'll leave this open and take care of it for the next release.

**Comment by saghul** [comment]
Version 2.1.0 is out and binary wheels are uploaded. Closing!
